### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by Abdusalamstd** [kompasim/UyghurScript#1]
🎈ئەرەب يېزىقى ئاساسىدىكى تەرجىمىتىر ياكى پىروگىرامما تىلى ھەققىدە ئوي-پېكىر ئورتاقلاشساق.

**Comment by Atypicalim** [comment]
مىنىڭچە گىرامماتىكىنى تۈزۈپ چىققىلى بولغان ئىكەن ئەرەپ يېزىقىمۇ تەسكە توختىمايدۇ.
مىنىڭ لاتىن يېزىقى ئىشلىتىشىم پەقەت كومپىيوتېرىمدا كىرگۈزگۈچ بولماسلىقى ۋە VScode دا ئوڭنى سول سولنى ئوڭ قىلىمەن دەپ ۋاقىت ئىسراپ قىلىشنى خالىمىغىنىمدا . ھازىرقى بۇ ئىنكاسنىمۇ ئىزدە تور بېتىنىڭ كىرگۈزگۈچىسىگە يېزىپ ئولتۇرۇپتىمەن.
ئەگەر ھازىرقى بۇ پىروگراممىنى ئەرەپ يېزىقىغا ئۆزگەرتىش توغرا كەلسە `tokenizer:tokenize` فونكىسىيەسىنى تەتۈر دەۋرىيلەيدىغان قىلىپ ھالقىلىق سۆزلەرنى ئالماشتۇرۇپ قويساقلا بولدى . مەسلىگە كەلسەك شۇ ياخشىراق ئوڭنى سول سولنى ئوڭ قىلىپ جاپا سالدىغان تەھرىرلىگۈچنىڭ بولماسلىقىدا . مەسلەن ئەرەپ يېزىقىغا لاتىن يېزىقى ۋە سان قۇشۇلۇپ يېزىلغاندا تەھرىرىلىگۈچتە ناھايىتى ئاسان قالايمىقانلىشىپ كىتىدۇ .

**Comment by Atypicalim** [comment]
تەرجىمە پىروگراممىسىغا كەلسەك بۇ جەھەتتە ئىزدىنىپ باقماپتىمەن. ئەمما بۇرۇن بىر ئاۋازلىق يادەمچى يېزىش توغرىسدا ئۇرۇنۇپ باققان . مىنىڭ يۇلۇققان ۋە ھەل قىلىش تەسكە توختىغان مەسىلەم بۇغۇمغا ئايرىش، سۆز تۈپى ۋە قۇشۇمچىنى ئايرىشتا بولغان . بۇ بەش ئالتە يىل بۇرۇنقى گەپ ، 中国知网 دىن جىق ماقالىلەرنى كۈرۈپ پايدىلانغان بولساممۇ يەنىلا ئاجىز كەلگەن . ھازىر بىلمىدىم ياخشىراق ئۈنۈمى يۇقىرىراق ئۇسۇل بارمۇ يوق.
گوگۇلنىڭ تەرجىمانىغا قاراپ باشقىلارنى بۇ مەسلىلەرنى ھەل قىلىپمۇ بولدى دەپ ئويلىدىم. ئوي پىكىرلىرىڭىز بولسا ئورتاقلىشىشىڭىزنى ئۈمۈت قىلىمەن

**Comment by Abdusalamstd** [comment]
[PNG](https://github.com/Abdusalamstd/XeLaTEX/blob/main/readme/4.png)
مەن يېقىندا مۇشۇ تەرجىمىلىنىش پىرىنسىپى 
编译原理
نى ئۆگەنگەن ئىدىم.
كىيىن ئىچىم پۇشۇپ مۇشۇنداق يەرلىك پىروگىرامما تىلىغا سەل قىززىقىپ قالغان.، كىيىن مەن ئۆگەنگەن بويىچە
词法分析，语法分析，语义分析
قاتارلىقلار ئۈستىدە بىرقاتار تەھلىل قىلىپ كۆرگەن ئىدىم، ھەتتا يېڭى پىروگىرمما تىلىدىكى ئاچقۇچلۇق سۆز، مىقدار، ھۆكۈملۈك،دەۋرىيلىك قاتارلىق ھالقىلىق سۆزلەرنىڭ ئەڭ ئاددىي چۈشىنىشلىك ئىپادىلىنىشلىرىنى رەتلەپ چىققان ئىدىم، شۇڭا سىزنىڭ بۇ لۇئا دا يېزىلغان پىروگىراممىغا بەكلا قىززىقتىم.
مەن خىيالىمدىكى يەرلىك پىرىگىرامما تىلىدىكى ھالقىلىق سۆزلەرنى يېزىپ رەتلەپ قويغان ئىدىم، سۆزلەرنىڭ بىرقىسمى تۆۋەندىكىدەك:
سانلار قىسمى: پۈتۈن، پارچە، ھەرپ، تىزىق، توپلام، جەدۋەل، ساندۇق
ھۆكۈملۈك ۋە دەۋرىيلىك: ئەگەر، ياكى، پاس، قايتا، تەكرار، تاكى،سەكرە
ھۆججەت ۋە كىرگۈزۈش چىقىرىش: ئاچ، ياپ، ئوقۇ، ياز،سۈز، ئالماش، سانا، كۆرسەت
ئەمەللەر: تەڭ، بەر، ئۆچۈر، قوش، ئال، بۆل، كۆپەيىت
باشقىلار: فۇنكىسيە، چاقىر، ئىمپورت، ئىكىسپورت....

دىمەكچى يۇقارقىدەك مۇشۇنداق تۈپ سۆزلەرنى رەتلىگەن، ئۈستىدىكى شۇلارنىڭ بىرقىسمى. شۇڭا مەن سىزنىڭ بۇ پىروگىراممىڭىزنى كۆرۈپ باشقىچە قىززىقىپ قالدىم. ھەقىقەتەن ياخشى يېزىپسز  ، ئەجىرلىك بولۇڭ.

**Comment by Atypicalim** [comment]
قارىغاندا بەكرەك تەپسىلىي ئويلىشىپسىز ، مەن نۇرغۇنلىرىنى تېخى ئويلاپ يەتمىدىم ياكى تاشلىۋەتتىم . 
ھازىرچە list ۋە map نى ئىشقا ئاشۇرۇش ۋە باشقا UyghurScript ھۆججىتدىن كود ئەكىرىپ ئىشلىتىشنى قوللاش پىلانىملا بار . ئۇنىڭدىن ئارتۇقچە جىق ۋاقتىمنى سەرىپ قىلماسلىقىم مۇمكىن . 
ئەگەر ئۈزىڭىز بىرنى يېزىپ باققۇڭىز بولسا lua تىلىنى بىر كۈرۈپ بېقىڭ . سىز رەتلىگەندەك ئۇنچە جىق تىل ئالاھىدىلىكى ۋە ئىقدىدارلار بىھاجەت . بىر پاتمان نەرسىنى تىزىۋالسىڭىز يېرىمى يېزىپ بۇلالماي تۇرۇپلا چارچاپ قالىسىز . lua ئاددىي ئەمما ھەممىنى قىلغىلى بۇلىدۇ . سىزمۇ شۇنداراق لايھەلىسىڭىز تىزرق ئەمەلگە ئاشۇرالايسىز .
ئۇنىڭدىن سىرىت تىلنىڭ گىرامماتىكىسى بولغاندىن سىرىت قۇرال ئامبارلىرى بۇلشى كېرەك، بۇلارنى بىر ئادەمنىڭ تۇلۇقلاپ كىرەلىشى ناتايىن .ياخشى ئامال LLVM نى ئارقا سۇپا قىلىپ يېزىش ،پەقەت تىل گىراماتىكىسىنى يېزىپلا ئامبارلارغا شۇنى ئىشلەتسىڭىز بۇلىدۇ . ئەگەر بۇنى بەك ئاۋارىچىلىق كۆرسىڭىز ياكى ئۈزەم باشقا نەرسىلەنى قوشماي ياسايتىم دىسىڭىز مىنىڭدەك باشقا تىلنىڭ نەرسىلىرىنى ئەكىرىپ ئىشلەتكىلى بۇلدىغان كۆۋرۈك ياساپ قويسىڭىزمۇ بۇلىدۇ . 
ئەگەر باشقىلار ئىشلەتكۈدەك بىر تىل قىلىپ ياسايمە دىسىڭىز ياخشىسى LLVM نى چۈشىنىپ بېقىڭ. قىزىقىشا ياسايمە دىسىڭىز مەن دىگەندك lua نى كۈرۈپ بېقىڭ ، ئاددى گىراماتىكا بىلەنمۇ مۇكەممەل پروگرامما يېزىپ چىققىلى بۇلىدۇ . cpp دەك ھەممە ئالاھىدىلىكنى يىغىۋېلىش بىھاجەت .

**Comment by Abdusalamstd** [comment]
بولىدۇ كۆپ رەھمەت

**Comment by YishilNota** [comment]
https://github.com/YishilNota/just-thinking
mawu mining godeklerche qilghan hiyallirimti burunlarda , bek addi. chaplap qoyay.
